namespace Technicians.Api.Models

{
    public class BatteryStringInfo
    {
        public string CallNbr { get; set; }
        public int EquipId { get; set; }
        public string BatteryStringId { get; set; }
        public string Manufacturer { get; set; }
        public string BatteryHousing { get; set; }
        public string ModelNo { get; set; }
        public string SerialNo { get; set; }
        public string BatteryType { get; set; }
        public string EquipStatus { get; set; }
        public string BatteryDateCodeMonth { get; set; }
        public int? BatteryDateCodeYear { get; set; }
        public string Comments_Used { get; set; }
        public bool? Bulged_Check { get; set; }
        public string Bulged_PF { get; set; }
        public bool? Cracked_Check { get; set; }
        public string Cracked_PF { get; set; }
        public bool? Debris_Check { get; set; }
        public string Debris_PF { get; set; }
        public string Rotten { get; set; }
        public string VerifySaftey { get; set; }
        public string ContainerComments { get; set; }
        public string EnvironmentComments { get; set; }
        public double? BatteryVoltage { get; set; }
        public string BatVoltage_PF { get; set; }
        public double? PlusTerminalToGround { get; set; }
        public string PlusTerminal_PF { get; set; }
        public double? MinusTerminalToGround { get; set; }
        public string MinusTerminal_PF { get; set; }
        public double? DCChargingCurrent { get; set; }
        public string DCCharging_PF { get; set; }
        public double? ACRipple { get; set; }
        public string ACRipple_PF { get; set; }
        public double? ACRippleCurrent { get; set; }
        public string VoltageStatus { get; set; }
        public string PlusTermStatus { get; set; }
        public string MinusTermStatus { get; set; }
        public string DCChargingStatus { get; set; }
        public string ACRippleStatus { get; set; }
        public string ACRippleCurrentStatus { get; set; }
        public string InterCellStatus { get; set; }
        public string TorqueStatus { get; set; }
        public string Comment { get; set; }
        public string PlusWrapped_PF { get; set; }
        public bool? PlusWrapped_Check { get; set; }
        public bool? PlusSulfated_Check { get; set; }
        public bool? PlusMisPos_Check { get; set; }
        public bool? Missing_Check { get; set; }
        public string Missing_PF { get; set; }
        public bool? Broken_Check { get; set; }
        public bool? NeedsCleaning_Check { get; set; }
        public string PlatesComments { get; set; }
        public string WaterLevel_T { get; set; }
        public string WaterLevel_PF { get; set; }
        public string ElectrolytesComments { get; set; }
        public string BatteryTemp_PF { get; set; }
        public int? Temp { get; set; }
        public int? Quantity_Used { get; set; }
        public int? TobeMonitored { get; set; }
        public string Reason_Replace { get; set; }
        public string FloatVoltS { get; set; }
        public string FloatVoltV { get; set; }
        public string IntercellConnector { get; set; }
        public bool? ReplaceWholeString { get; set; }
        public DateTime? CreatedOn { get; set; }
        public DateTime? LastModified { get; set; }
        public string Maint_Auth_Id { get; set; }
        public string RepMonCalc { get; set; }
        public int? BatteryPackCount { get; set; }
        public string IndBattDisconnect { get; set; }
        public string IndBattInterConn { get; set; }
        public string RackIntegrity { get; set; }
        public string VFOperation { get; set; }
        public string Location { get; set; }
        public string ReadingType { get; set; }
        public bool? SaveAsDraft { get; set; }
        public bool? chkmVAC { get; set; }
        public bool? chkStrap { get; set; }
        public int? BattTemp { get; set; }
        public string BattTemp_PF { get; set; }
        public string BatteryTypeName { get; set; }
        public string StringType { get; set; }
        public string BattTerminalS { get; set; }
        public string BattTerminalT { get; set; }
        public string BattTypeTerminal { get; set; }
        public string BattProActiveReplace { get; set; }
        public string ReadingMethod { get; set; }
        public bool? chkGraph { get; set; }
        public int? code { get; set; }
        public string Message { get; set; }
        public double? Resistance { get; set; }
        public string Resistance_PF { get; set; }
        public double? CodeTorque { get; set; }
        public string CodeTorque_PF { get; set; }
        public bool? NegWrapped_Check { get; set; }
        public string NegWrapped_PF { get; set; }
        public bool? NegSulfated_Check { get; set; }
        public bool? NegMisPos_Check { get; set; }
        public string BothActMat_PF { get; set; }
        public bool? BothActMat_Check { get; set; }
        public bool? ActPosMat_Check { get; set; }
        public bool? Other_Check { get; set; }
        public string SedimentsComments { get; set; }
        public bool? MissingCovers_Check { get; set; }
        public string MissingCovers_PF { get; set; }
        public bool? BrokenCovers_Check { get; set; }
        public bool? NeedsCleaningCovers_Check { get; set; }
        public bool? MissingSep_Check { get; set; }
        public string MissingSep_PF { get; set; }
        public bool? QuartBelow_Check { get; set; }
        public string QuartBelow_PF { get; set; }
        public bool? HalfBelow_Check { get; set; }
        public string HalfBelow_PF { get; set; }
        public bool? ThrbyFourBelow_Check { get; set; }
        public string ThrbyFourBelow_PF { get; set; }
        public string WaterFill_YN { get; set; }
        public string SepComments { get; set; }
        public int? Quantity_Needed { get; set; }
        public string ImmedActionOpen { get; set; }
        public string UpgradeNoOpenAge { get; set; }
        public string UpgradeNoOpen { get; set; }
        public int? RoomTemp { get; set; }
        public string PositivePost { get; set; }
        public string NegativePost { get; set; }
        public string PostSeals { get; set; }
        public string BatteryDisc { get; set; }
        public string MiscHardware { get; set; }
        public string SealsComments { get; set; }
        public string HardwareComments { get; set; }
        public string ManufDate_PF { get; set; }
        public string ManufDate { get; set; }
    }
}

