// Order Request models matching the backend DTOs and legacy form

export interface OrderRequestDto {
  rowIndex: number;
  orderType?: string | null;  // Department in legacy (Repair, ASSY)
  requester?: string | null;
  dcgPartNo?: string | null;   // DCG P/N# in legacy
  manufPartNo?: string | null; // Manuf P/N# in legacy  
  vendor?: string | null;
  qtyNeeded?: number | null;   // Qty Needed in legacy
  poNumber?: string | null;    // PO in legacy
  orderDate?: Date | null;     // Order Date in legacy
  arriveDate?: Date | null;    // Arrive Date in legacy
  notes?: string | null;       // Notes in legacy
  status?: string | null;      // Status dropdown in legacy
  lastModifiedBy: string;
}

export interface OrderRequestResponseDto extends OrderRequestDto {
  createdBy?: string | null;
  createdOn?: Date | null;
  modifiedBy?: string | null;
  modifiedOn?: Date | null;
  archive: boolean;
}

// Request interface for save/update operations
export interface SaveUpdateOrderRequestRequest extends OrderRequestDto {
  // Inherits all properties from OrderRequestDto
}

// Response interface for save/update operations
export interface SaveUpdateOrderRequestResponse {
  rowIndex: number;
  message: string;
  uploadedFiles?: UploadedFileInfo[];
}

// File upload response information
export interface UploadedFileInfo {
  fileName: string;
  filePath: string;
  fileUrl?: string;
  size: number;
  uploadStatus: 'Success' | 'Failed';
  errorMessage?: string;
}

// Status options for dropdown
export interface OrderRequestStatusOption {
  value: string;
  label: string;
}

// Order type options for dropdown
export interface OrderRequestTypeOption {
  value: string;
  label: string;
}

// Filter interface for order request queries
export interface OrderRequestFilter {
  status?: string;
  orderType?: string;
  requester?: string;
  dateFrom?: Date;
  dateTo?: Date;
}

// Auto Generated ID interface for legacy compatibility
export interface AutoGeneratedId {
  year: string;
  month: string;
  day: string;
  id: string;
}

// File attachment interface
export interface OrderRequestAttachment {
  name: string;
  creationTime: Date;
  fullName: string;
  size?: number;
}

// Constants for dropdowns (matching legacy options)
export const ORDER_REQUEST_STATUS_OPTIONS: OrderRequestStatusOption[] = [
  { value: 'NEW', label: 'New' },
  { value: 'ORD', label: 'Ordered' },
  { value: 'SHI', label: 'Shipped' },
  { value: 'BOR', label: 'Back Ordered' },
  { value: 'CAN', label: 'Cancelled' },
  { value: 'COM', label: 'Completed' }
];

export const ORDER_REQUEST_TYPE_OPTIONS: OrderRequestTypeOption[] = [
  { value: 'Repair', label: 'Repair' },
  { value: 'Assy', label: 'ASSY' }
];